# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Dart

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Flutter Install flutter
        uses: subosito/flutter-action@v2.4.0
        with:
            flutter-version: '2.8.0'
            channel: 'stable'
      - run: flutter --version

      - name: Install dependencies  
        run: flutter clean && flutter pub get

      - name: Analyze project source
        run: flutter analyze

      - name: Run tests
        run: flutter test --coverage
      
      - name: Upload code coverage.
        uses: codecov/codecov-action@v1
        with:
          token: ${{secrets.CODECOV_TOKEN}}
          file: coverage/lcov.info
